config/routes.rb
Rails.application.routes.draw do
  root "static_pages#main"
  get "main", to: "static_pages#main"
  get "contact", to: "static_pages#contact"
  get "about", to: "static_pages#about"
  get "our_work", to: "static_pages#our_work"
  get "services", to: "static_pages#services"

  resources :splits, only: [:index, :show]
  resources :monoblocks, only: [:index, :show]
  resources :cells, only: [:index, :show]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cell.rb
class Cell < ApplicationRecord
  acts_as :product

  has_and_belongs_to_many :monoblocks
  has_and_belongs_to_many :splits

  validates :temperature_range, length: {maximum: 20}
  validates :space, numericality: {only_float: true}, allow_blank: true
  validates :dimensions, length: {maximum: 30}
  validates :net_weight, numericality: true, allow_blank: true
  validates :packed_sizes, length: {maximum: 30}

end

app/models/monoblock.rb
class Monoblock < ApplicationRecord
  acts_as :product

  has_and_belongs_to_many :cells

  validates :refrigerant, length: {maximum: 20}
  validates :temperature_condition, length: {maximum: 20}
  validates :voltage, length: {maximum: 20}
  validates :power_usage, numericality: {only_float: true}, allow_blank: true
  validates :dimensions, length: {maximum: 30}
  validates :net_weight, numericality: true, allow_blank: true
  validates :packed_sizes, length: {maximum: 30}

end

app/models/product.rb
class Product < ApplicationRecord
  actable
  mount_uploader :avatar, AvatarUploader

  after_initialize :set_defaults, unless: :persisted?

  validates :title, presence: true, length: { maximum: 80 }, uniqueness: true
  validates :price, numericality: true

  def translated_actable_type
    I18n.t("#{self.actable_type.downcase}")
  end

  def set_defaults
    self.price ||= '0'
  end
end

app/models/split.rb
class Split < ApplicationRecord
  acts_as :product

  has_and_belongs_to_many :cells

  validates :refrigerant, length: {maximum: 20}
  validates :temperature_condition, length: {maximum: 20}
  validates :voltage, length: {maximum: 20}
  validates :power_usage, numericality: {only_float: true}, allow_blank: true
  validates :inner_dimensions, length: {maximum: 30}
  validates :external_dimensions, length: {maximum: 30}
  validates :net_weight, numericality: true, allow_blank: true
  validates :packed_sizes, length: {maximum: 30}

end

app/models/work_object.rb
class WorkObject < ApplicationRecord
  has_many :work_photos, dependent: :destroy
  accepts_nested_attributes_for :work_photos

  validates :title, presence: true
end

app/models/work_photo.rb
class WorkPhoto < ApplicationRecord
  belongs_to :work_object
  mount_uploader :image, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cells_controller.rb
class CellsController < InheritedResources::Base
  def index
    @cells = Cell.page(params[:page]).per(12)
    @product = Product.where(actable_type: "Cell")
  end
  def show
    @cell = Cell.find(params[:id])
    @product = Product.find_by(actable_type: "Cell", actable_id: params[:id])
    @additional = @cell.monoblocks + @cell.splits
  end
end

app/controllers/monoblocks_controller.rb
class MonoblocksController < InheritedResources::Base

  def index
    @monoblocks = Monoblock.page(params[:page]).per(12)
    @product = Product.where(actable_type: "Monoblock")
  end

  def show
    @monoblock = Monoblock.find(params[:id])
    @product = Product.find_by(actable_type: "Monoblock", actable_id: params[:id])
    @additional = @monoblock.cells
  end
end

app/controllers/splits_controller.rb
class SplitsController < InheritedResources::Base

 def index
    @splits = Split.page(params[:page]).per(12)
    @product = Product.where(actable_type: "Split")
  end

  def show
    @split = Split.find(params[:id])
    @product = Product.find_by(actable_type: "Split", actable_id: params[:id])
    @additional = @split.cells
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def main
  end
  def contact
  end
  def about
  end
  def our_work
    @work_object = WorkObject.all
  end
  def services
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def product_avatar(model)
    if model.avatar.present?
      model.avatar.url
    elsif model.image_link.present?
      model.image_link
    else
      asset_path("no_photo.png")
    end
  end
end

app/helpers/cells_helper.rb
module CellsHelper
end

app/helpers/monoblocks_helper.rb
module MonoblocksHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/splits_helper.rb
module SplitsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def photo_for_slider(photo, index)
    if photo.image.present?
      image_tag("#{photo.image}", alt: "#{index+1} slide")
    elsif photo.image_link.present?
      image_tag("#{photo.image_link}", alt: "#{index+1} slide")
    else
      image_tag("no_photo.png", alt: "#{index+1} slide")
    end
  end
end

app/views/cells/index.html.erb
<div class="product-container">
  <div class="model-title">
    <h1>Холодильные камеры</h1>
  </div><!-- /title -->
  <div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-9 col-xl-9 modal-text">
      <p>Холодильные камеры собираются из сэндвич-панелей и имеют сборно-разборную конструкцию. Предназначены для охлаждения и хранения в течение определенного периода продуктов, лекарственных средств, химических реагентов, цветов, изделий из натурального меха и других товаров и продукции. Холодильные установки устанавливаются в доме, небольших и крупных магазинах, складах и на предприятиях разной отрасли. Могут эксплуатировать внутри отапливаемых и неотапливаемых помещений, а также на открытом воздухе или под навесом при температуре окружающей среды от -30С до +40С и показатели относительной влажности максимум 80%. 
      </p>
    </div>
  </div>
  <div class="row row-flex row-flex-wrap">
    <% @cells.each do |cell| %>
      <div class="col-12 col-sm-6 col-md-6 col-lg-4 col-xl-3-custom">
        <div class="product-item">
          <div class="product-image">
            <%= image_tag(product_avatar(cell), size: "200x250")  %>
          </div><!-- /product-image -->

          <div class="product-title">
            <h3><%=link_to cell.title, cell_path(cell.id) %></h3>
          </div><!-- /cproduct-title -->

          <div class="product-table">
            <table class="table table-striped">
              <tbody>
                <tr>
                  <th scope="row">Объем, м3</th>
                  <td><%= cell.space %></td>
                </tr>
                <tr>
                  <th scope="row">Габаритные размеры, мм</th>
                  <td><%= cell.dimensions %></td>
                </tr>
                <tr>
                  <th scope="row">Цена, руб. с НДС</th>
                  <td><%= cell.price %></td>
                </tr>
              </tbody>
            </table>
          </div><!-- /product-table -->

          <div class="link-to-detail">
            <%=link_to "Подробнее", cell_path(cell.id)%>
          </div><!-- /link-to-detail -->
        </div><!-- /product-item -->
      </div><!-- /col-md-3 -->
    <% end %>
  </div>
  <div class="pagination-conteiner">
    <div class="row">
      <div class="col-12 col-sm-12 col-md-12 col-lg-12">
        <%= paginate @cells %>
      </div>
    </div>
  </div>
</div>

app/views/cells/show.html.erb
<div class="product-show">
  <div class="model-title">
    <h1><%= @cell.title %></h1>
  </div>
  <div class="row main-info">
    <div class="col-12 col-sm-12 col-md-5 col-lg-4 col-xl-4 product-image">
      <%= image_tag(product_avatar(@cell), size: "260x380") %>
    </div><!-- col-md-2 -->
    <div class="col-12 col-sm-12 col-md-7 col-lg-8 col-xl-8">
      <div class="product-table-show">
        <h3>Характеристики:</h3>
        <table class="table table-striped">
          <tbody>
            <tr>
              <th scope="row">Диапазон температуры окружающего воздуха</th>
              <td><%= @cell.temperature_range %></td>
            </tr>
            <tr>
              <th scope="row">Объём, м3</th>
              <td><%= @cell.space %></td>
            </tr>
            <tr>
              <th scope="row">Габаритные размеры, мм</th>
              <td><%= @cell.dimensions %></td>
            </tr>
            <tr>
              <th scope="row">Вес нетто, кг</th>
              <td><%= @cell.net_weight %></td>
            </tr>
            <tr>
              <th scope="row">Размеры в упаковке</th>
              <td><%= @cell.packed_sizes %></td>
            </tr>
            <tr class="price">
              <th scope="row">Цена, руб. с НДС</th>
              <td><%= @cell.price %></td>
            </tr>
          </tbody>
        </table>
        <div class="button-wrapper">
          <a class="btn popup-btn" href="#">Получить консультацию</a>
        </div>
      </div><!-- product-table -->
    </div><!-- col-md-10 -->
    <div class="popup-wrap">
      <div class="popup-box">
        <h2>Тел. 8-(495)-997-00-14</h2>
        <a class="close-btn popup-close" href="#">
          <span class="glyphicon glyphicon-remove"></span>
        </a>
      </div>
    </div>
  </div><!-- row -->


  <%= render partial: 'partial/additional', object: @additional %>

</div><!-- product-show -->

app/views/layouts/_footer.html.erb
<div class="container-fluid text-center text-md-left footer-main">
  <div class="row">
    <div class="col-12 col-sm-12 col-md-6 col-lg-6">
      <h4 class="text-uppercase">DopHolod.ru</h4>
      <p class="footer-text">Холодильные камеры и другое оборудование для вашего бизнеса. <br>Подбор, доставка и обслуживание по Москве и области.</p>
    </div>
    <div class="custom-col-6 col-sm-6 col-md-3 col-lg-3">
      <h5 class="text-uppercase">Каталог</h5>
      <ul class="footer-list">
        <li>
          <%= link_to "Холодильные камеры", cells_path %>
        </li>
        <li>
          <%= link_to "Моноблоки", monoblocks_path %>
        </li>
        <li>
          <%= link_to "Сплит-Системы", splits_path %>
        </li>
      </ul>
    </div>
    <div class="custom-col-6 col-sm-6 col-md-3 col-lg-3">
      <h5 class="text-uppercase">О компании</h5>
      <ul class="footer-list">
        <li>
          <%= link_to "Главная", root_path %>
        </li>
        <li>
          <%=link_to "Услуги", services_path %>
        </li>
        <li>
          <%=link_to "Наши работы", our_work_path %>
        </li>
        <li>
          <%=link_to "О нас", about_path%>
        </li>
        <li>
          <%=link_to "Контакты", contact_path %>
        </li>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-12">
      <div class="footer-down text-center py-3">© 2019 production:
        <a href=""> dopholod.ru</a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="nav navigation">
  <div class="nav-title">
    <!--<a href="javascript:void(0);" class="icon" onclick="myFunction()">
      <i class="fa fa-bars"></i>
    </a>
  -->
    <button class="navbar-toggler icon" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="fa fa-bars"></span>
    </button>
    <div class="model-title">
      <h1><%= link_to "DopHolod", root_path%></h1>
    </div>
  </div>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="nav">
      <li class="nav-item">
        <%= link_to "Холодильные камеры", cells_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Моноблоки", monoblocks_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Сплит-системы", splits_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%=link_to "Услуги", services_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%=link_to "Наши работы", our_work_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%=link_to "О нас", about_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%=link_to "Контакты", contact_path, class: "nav-link" %>
      </li>
    </ul>
  </div><!-- /menu-left -->
  <div class="social">
    <ul>
      <li class="item1">
        <%= link_to "", "https://vk.com/public181784567" %>
      </li>
      <li class="item2">
        <%= link_to "", "https://www.instagram.com/dopholod/" %>
      </li>
      <li class="item3">
        <%= link_to "", "https://www.facebook.com" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dopholod</title>
    <%= csrf_meta_tags %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'  %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>

    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- left menu -->
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans+Extra+Condensed" rel="stylesheet">
    <!-- model title -->
    <link href="https://fonts.googleapis.com/css?family=Russo+One" rel="stylesheet">
  </head>
  <body>

    <div class="container-fluid">
      <div class="row">
        <%= render 'layouts/navbar' %>

        <div class="main">
          <%= yield %>
        </div><!-- /main -->

        <!-- Footer -->
        <div class="page-footer font-small">
          <%= render 'layouts/footer' %>
        </div>

      </div><!-- /row -->
    </div> <!-- /container -->

  </body>
</html>

app/views/monoblocks/index.html.erb
<div class="product-container">
  <div class="model-title">
    <h1>Моноблоки</h1>
  </div><!-- /title -->
  <div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-9 col-xl-9 modal-text">
      <p>Для генерации холода существует несколько разновидностей холодильных установок. Холодильный моноблок — агрегат , используемая для охлаждения внутреннего пространства холодильной камеры и поддержания определенной температуры. Они классифицируются по температуре охлаждения камеры, мощности, холодопроизводительности, объемом и напряжением. Моноблоки изготовлены в одном корпусе, в котором соединены компрессор с конденсатором и воздухоохладитель. Поставляются в готовом к работе виде, то есть они испытаны и заправлены холодильным агентом.
      </p>
    </div>
  </div>
  <div class="row row-flex row-flex-wrap">
    <% @monoblocks.each do |monoblock| %>
      <div class=" col-12 col-sm-6 col-md-6 col-lg-4 col-xl-3-custom">
        <div class="product-item">
          <div class="product-image">
            <%= image_tag(product_avatar(monoblock), size: "200x250") %>
          </div><!-- /product-image -->

          <div class="product-title">
            <h3><%=link_to monoblock.title, monoblock_path(monoblock.id) %></h3>
          </div><!-- /cproduct-title -->

          <div class="product-table">
            <table class="table table-striped">
              <tbody>
                <tr>
                  <th scope="row">Габаритные размеры, мм</th>
                  <td><%= monoblock.dimensions %></td>
                </tr>
                <tr>
                  <th scope="row">Темп. режим, °C</th>
                  <td><%= monoblock.temperature_condition %></td>
                </tr>
                <tr>
                  <th scope="row">Цена, руб. с НДС</th>
                  <td><%= monoblock.price %></td>
                </tr>
              </tbody>
            </table>
          </div><!-- /product-table -->

          <div class="link-to-detail">
            <%=link_to "Подробнее", monoblock_path(monoblock.id)%>
          </div><!-- /link-to-detail -->
        </div><!-- /product-item -->
      </div><!-- /col-md-3 -->
    <% end %>
  </div>
  <div class="pagination-conteiner">
    <div class="row">
      <div class="col-12 col-sm-12 col-md-12 col-lg-12">
        <%= paginate @monoblocks %>
      </div>
    </div>
  </div>
</div>

app/views/monoblocks/show.html.erb
<div class="product-show">
  <div class="model-title">
    <h1><%= @monoblock.title %></h1>
  </div>
  <div class="row main-info">
    <div class="col-md-4 product-image">
      <%= image_tag(product_avatar(@monoblock), size: "260x380") %>
    </div><!-- /col-md-2 -->
    <div class="col-md-8">
      <div class="product-table-show">
        <h3>Характеристики:</h3>
        <table class="table table-striped">
          <tbody>
            <tr>
              <th scope="row">Хладагент</th>
              <td><%= @monoblock.refrigerant %></td>
            </tr>
            <tr>
              <th scope="row">Температурный режим, °С</th>
              <td><%= @monoblock.temperature_condition %></td>
            </tr>
            <tr>
              <th scope="row">Напряжение в сети, в/ф/гц</th>
              <td><%= @monoblock.voltage %></td>
            </tr>
            <tr>
              <th scope="row">Maксимальное энергопотребление, кВт</th>
              <td><%= @monoblock.power_usage %></td>
            </tr>
            <tr>
              <th scope="row">Вес нетто, кг</th>
              <td><%= @monoblock.net_weight %></td>
            </tr>
             <tr>
              <th scope="row">Габаритные размеры</th>
              <td><%= @monoblock.dimensions %></td>
            </tr>
            <tr>
              <th scope="row">Размеры в упаковке</th>
              <td><%= @monoblock.packed_sizes %></td>
            </tr>
            <tr class="price">
              <th scope="row">Цена, руб. с НДС</th>
              <td><%= @monoblock.price %></td>
            </tr>
          </tbody>
        </table>
        <div class="button-wrapper">
          <a class="btn popup-btn" href="#">Получить консультацию</a>
        </div>
      </div><!-- /product-table -->
    </div><!-- /col-md-10 -->
    <div class="popup-wrap">
      <div class="popup-box">
        <h2>Тел. 8-(495)-997-00-14</h2>
        <a class="close-btn popup-close" href="#">
          <span class="glyphicon glyphicon-remove"></span>
        </a>
      </div>
    </div>
  </div><!-- /row -->

  <%= render partial: 'partial/additional', object: @additional %>

</div><!-- /product-shhow -->

app/views/partial/_additional.html.erb
<% if additional.present? %>
  <div class="additional-products">
      <div class="model-title">
        <% if @product.actable_type == "Cell" %>
          <h3>Агрегаты подходят к этой камере:</h3>
        <% elsif @product.actable_type == "Split" || @product.actable_type == "Monoblock"%>
          <h3>Камеры подходят к этому агрегату:</h3>
        <% end %>
      </div>
    <% if additional.count <= 4 %>
      <div class="row">
        <div class="col-12 col-sm-12 col-md-11 col-lg-11 col-xl-11 no-carousel">
          <% additional.each do |item| %>
            <div class="item">
              <div class="carousel-col">
                <div class="block">
                  <div class="product-image">
                    <%= image_tag(product_avatar(item), size: "140x200") %>
                  </div><!-- product-image -->
                  <div class="product-title product-title-center">
                    <h3><%=link_to item.title, eval("#{item.class.to_s.downcase}_path(item.id)")%></h3>
                  </div><!-- product-title product-title-center -->
                </div><!-- block -->
              </div><!-- carousel-col -->
            </div><!-- item -->
          <% end %>
        </div><!-- col-md-11 no-carouse -->
      </div><!-- row -->
    <% else %>
    <!-- carousel -->
      <div class="row">
        <div class="col-11 col-sm-11 col-md-11 col-lg-11 col-xl-11 col-centered">
          <div id="carousel" class="carousel slide" data-ride="carousel" data-type="multi" data-interval="4000">
            <div class="carousel-inner col-centered carousel-inner-cust">
              <% additional.each_with_index do |item, index| %>
                <% if index == 0 %>
                  <div class="item active">
                <% else %>
                  <div class="item">
                <%end%>
                <div class="carousel-col">
                  <div class="block">
                    <div class="product-image">
                      <%= image_tag(product_avatar(item), size: "140x200") %>
                    </div>
                    <div class="product-title product-title-center">
                      <h3><%= link_to item.title, eval("#{item.class.to_s.downcase}_path(item.id)")%></h3>
                    </div>
                  </div>
                </div>
              </div>
              <% end %>
            </div>
            <!-- Controls -->
            <div class="left carousel-control">
              <a href="#carousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
            </div><!-- left carousel-control -->
            <div class="right carousel-control">
              <a href="#carousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div><!-- right carousel-control -->
          </div><!-- carousel slide -->
        </div><!-- col-md-11 col-centered -->
      </div><!-- row -->

    <%end%>
  </div>
<% end %>

app/views/splits/index.html.erb
<div class="product-container">
  <div class="model-title">
    <h1>Сплит-системы</h1>
  </div><!-- /title -->
  <div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-9 col-xl-9 modal-text">
      <p>Холодильные сплит-системы - это комплекс из двух блоков, применяющихся для поддержания заданного режима температур в холодильной камере. Монтируются там, где невозможно применение холодильного моноблока. Внутренний и наружный блоки соединены между собой медными трубками (в теплоизоляции) и кабелем питания управления. Холодильные сплит системы POLAIR предназначены для охлаждения внутреннего пространства холодильной камеры, объемом до 51 м3 при внешней температуре окружающего воздуха от +10°С до +40°С.Цена эксплуатации оборудования этого класса достаточно низкая, что обуславливает его популярность.
      </p>
    </div>
  </div>
  <div class="row row-flex row-flex-wrap">
    <% @splits.each do |split| %>
      <div class="col-12 col-sm-6 col-md-6 col-lg-4 col-xl-3-custom">
        <div class="product-item">
          <div class="product-image">
            <%= image_tag(product_avatar(split), size: "200x250") %>
          </div><!-- /product-image -->

          <div class="product-title">
            <h3><%=link_to split.title, split_path(split.id) %></h3>
          </div><!-- /cproduct-title -->
          <div class="product-table">
            <table class="table table-striped">
              <tbody>
                <tr>
                  <th scope="row">Темп. режим, °C</th>
                  <td><%= split.temperature_condition %></td>
                </tr>
                <tr>
                  <th scope="row">Габаритные размеры внешнего блока, мм</th>
                  <td><%= split.external_dimensions %></td>
                </tr>
                <tr>
                  <th scope="row">Габаритные размеры внутреннего блока, мм</th>
                  <td><%= split.inner_dimensions %></td>
                </tr>
                <tr>
                  <th scope="row">Цена, руб. с НДС</th>
                  <td><%= split.price %></td>
                </tr>
              </tbody>
            </table>
          </div><!-- /product-table -->

          <div class="link-to-detail">
            <%=link_to "Подробнее", split_path(split.id)%>
          </div><!-- /link-to-detail -->
        </div><!-- /product-item -->
      </div><!-- /col-md-3 -->
    <% end %>
  </div>
  <div class="pagination-conteiner">
    <div class="row">
      <div class="col-12 col-sm-12 col-md-12 col-lg-12">
        <%= paginate @splits %>
      </div>
    </div>
  </div>
</div>

app/views/splits/show.html.erb
<div class="product-show">
  <div class="model-title">
    <h1><%= @split.title %></h1>
  </div>
  <div class="row main-info">
    <div class="col-md-4 product-image">
      <%= image_tag(product_avatar(@split), size: "260x380") %>
    </div><!-- /col-md-2 -->
    <div class="col-md-8">
      <div class="product-table-show">
        <h3>Характеристики:</h3>
        <table class="table table-striped">
          <tbody>
            <tr>
              <th scope="row">Хладагент</th>
              <td><%= @split.refrigerant %></td>
            </tr>
            <tr>
              <th scope="row">Температурный режим, °С</th>
              <td><%= @split.temperature_condition %></td>
            </tr>
            <tr>
              <th scope="row">Напряжение в сети, в/ф/гц</th>
              <td><%= @split.voltage %></td>
            </tr>
            <tr>
              <th scope="row">Maксимальное энергопотребление, кВт</th>
              <td><%= @split.power_usage %></td>
            </tr>
            <tr>
              <th scope="row">Вес нетто, кг</th>
              <td><%= @split.net_weight %></td>
            </tr>
            <tr>
              <th scope="row">Габаритные размеры внешнего блока, мм</th>
              <td><%= @split.external_dimensions %></td>
            </tr>
            <tr>
              <th scope="row">Габаритные размеры внутреннего блока, мм</th>
              <td><%= @split.inner_dimensions %></td>
            </tr>
            <tr class="price">
              <th scope="row">Цена, руб. с НДС</th>
              <td><%= @split.price %></td>
            </tr>
          </tbody>
        </table>
        <div class="button-wrapper">
          <a class="btn popup-btn" href="#">Получить консультацию</a>
        </div>
      </div><!-- /product-table -->
    </div><!-- /col-md-10 -->
    <div class="popup-wrap">
      <div class="popup-box">
        <h2>Тел. 8-(495)-997-00-14</h2>
        <a class="close-btn popup-close" href="#">
          <span class="glyphicon glyphicon-remove"></span>
        </a>
      </div>
    </div>
  </div><!-- /row -->

  <%= render partial: 'partial/additional', object: @additional %>

</div><!-- /product-shhow -->

app/views/static_pages/about.html.erb
<div class="product-container first-block-about">
  <div class="row">
    <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
      <div class="model-title">
        <h1>О нас</h1>
      </div>
      <div class="about-text">

        <p>Мы предоставляем широкого спектра услуг по сервису, монтажу и ремонту холодильного оборудования по оптимальным ценам. Работаем со стандартным и нестандартным торговым, промышленным холодильным оборудованием.</p>

        <p>Тесные связи с ведущими производителями и поставщиками гарантируют Вам установку качественного, сертифицированного оборудования и запасных частей.</p>

        <p>В наличии имеется весь необходимый холодильный инструмент, который нужен для проведения диагностики и ремонта холодильного оборудования, основная часть расходных материалов и запчастей. Кроме того, наши механики имеют более чем 5-летний опыт работы в холодильной отрасли, поэтому хорошо знают свое дело и выполняют его добросовестно.</p>
      </div>
    </div>
  </div>
</div>